import React from 'react';
import ReactDOM from 'react-dom';
import { App } from './App';

import './index.css';
import * as serviceWorker from './serviceWorker';

if (window.location.href.includes('/evening')) {
  document.write(
    'Donec dictum vitae nibh non aliquet. Praesent scelerisque lobortis congue. Fusce ac dui convallis, ultricies justo vitae, cursus mi. Pellentesque justo diam, euismod nec efficitur et, malesuada eget nunc. Phasellus sed ligula ac odio consectetur feugiat vel vitae lorem. Nam pretium a erat condimentum elementum. Aliquam sit amet nunc sollicitudin, fringilla lectus vitae, posuere nisi. Sed pharetra sem quis justo lobortis, id ultrices mauris scelerisque. Praesent varius orci sed elit accumsan varius. Curabitur id consectetur felis. Mauris pellentesque nisl sem, in tincidunt felis laoreet sit amet. Fusce dolor lorem, finibus et pulvinar ac, scelerisque vel lacus. Quisque dignissim hendrerit purus eget sagittis. Praesent erat est, bibendum quis turpis vitae, venenatis dignissim justo. Morbi vitae lacus cursus, sodales risus non, maximus metus. Sed gravida orci vel lacus placerat viverra.\n' +
      '\n' +
      'Vestibulum dapibus magna mollis sem cursus aliquet. Mauris at mauris commodo, laoreet risus porttitor, convallis diam. Donec lacinia congue risus, vitae auctor nulla. Nulla porta ut quam a viverra. Pellentesque nisl enim, laoreet sed cursus nec, tempus a ligula. Vestibulum sagittis elementum eros. Sed turpis lorem, interdum id diam in, condimentum fringilla neque. Nulla ut est ipsum. Cras lacinia sollicitudin purus ac blandit.\n' +
      '\n' +
      'Quisque ornare quis eros in interdum. Mauris feugiat congue sapien a consectetur. Vestibulum pellentesque risus eu mollis luctus. Fusce egestas non ipsum non rutrum. Ut eget molestie turpis, lobortis dignissim augue. Mauris in eros vel nunc mattis ultricies a blandit tortor. Nam egestas ac tellus quis faucibus. Nulla eu velit in tellus laoreet facilisis id at nulla. Mauris volutpat libero tellus, finibus congue diam volutpat ut. Mauris feugiat dictum turpis, ut maximus eros tempus pulvinar. Praesent vulputate nisi eget augue hendrerit, aliquet porta purus venenatis. Ut vulputate arcu ac orci mattis, sed maximus eros placerat.\n' +
      '\n' +
      'Pellentesque id justo justo. Ut quis lacinia nunc, id venenatis mi. Curabitur sit amet metus placerat, commodo magna quis, sodales tortor. Integer porta lacus urna, ac tempus libero rutrum id. Vestibulum dui turpis, rhoncus a mollis sit amet, interdum iaculis arcu. Duis eleifend mollis dictum. Nunc auctor hendrerit dolor, sed consectetur tortor vestibulum sed. Aliquam gravida tincidunt libero sit amet ultrices. Quisque dictum sem et fermentum iaculis. In tempor semper purus, a dapibus sem commodo quis. Mauris id commodo lectus. Duis vehicula est sem, sit amet dictum nisl vulputate quis.\n' +
      '\n' +
      'Nulla facilisi. Morbi eget risus feugiat dui pulvinar dapibus. Aenean nisl sapien, lacinia nec varius sit amet, eleifend id ex. Suspendisse quis feugiat sapien, vel interdum odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed feugiat odio sit amet orci efficitur, vel rhoncus nulla vehicula. Donec lobortis rhoncus ultricies. Aliquam in diam tellus. Duis porta ultrices venenatis. Nam dictum tristique ligula, nec porttitor nunc finibus a. Fusce sagittis pellentesque ipsum nec commodo. Ut congue mauris vel nisl pellentesque, nec fermentum urna vulputate. Suspendisse et rhoncus sem, non cursus sem. Donec et massa vel diam tristique dictum.\n' +
      '\n' +
      'In eget nulla cursus lacus bibendum volutpat quis ac felis. Suspendisse euismod sagittis ex, sit amet elementum velit condimentum id. Sed finibus ex nisl, et varius diam sodales blandit. Vivamus in sapien magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam vitae ante et magna pulvinar pharetra. Etiam ultrices porttitor tortor ac rhoncus. Donec quis mi at lorem bibendum congue vel vitae tortor. Fusce sit amet bibendum orci, in tincidunt magna.\n' +
      '\n' +
      'Pellentesque dui velit, placerat nec luctus sit amet, imperdiet a erat. Mauris scelerisque ut nisl ac commodo. Integer interdum libero vel sem maximus, nec tempus leo aliquet. Quisque a dolor non tellus facilisis hendrerit. Vestibulum ut neque varius, vehicula arcu a, semper ipsum. Aliquam vitae tincidunt ante, vitae porttitor tortor. Nunc posuere lectus et posuere maximus. Integer non ex id nisl auctor posuere. Fusce at sem feugiat, congue dolor ac, condimentum ex. Donec nibh elit, dignissim sed mattis vitae, pulvinar ac tellus. Nulla dapibus tempus blandit. Integer nec rhoncus neque. Praesent at sodales turpis, bibendum porta purus. Phasellus sed enim consectetur, porta sapien vel, luctus massa.\n' +
      '\n' +
      'Proin sodales turpis vel tristique commodo. Donec facilisis aliquet justo sed congue. Nam ac eros in sem fermentum convallis a ac ante. Suspendisse vitae risus euismod, posuere felis vitae, fringilla urna. Aenean sollicitudin ultricies nunc, at suscipit mauris consequat eget. Mauris finibus libero risus, nec ultrices enim fermentum ac. Donec sem tellus, faucibus ut libero quis, sodales vulputate justo. Fusce in facilisis orci. Vestibulum sed hendrerit odio. Suspendisse et ultricies nunc. Mauris eu nunc nec urna congue vulputate. Morbi vitae dapibus nisl. Aliquam aliquet venenatis ipsum ut gravida. Aenean viverra iaculis magna at tempor.\n' +
      '\n' +
      'Sed nec condimentum augue. Pellentesque et convallis quam. Aliquam sodales gravida eros, tempor ultricies augue tristique et. Praesent a turpis vitae massa faucibus bibendum. Phasellus varius, lacus non fermentum interdum, magna est egestas diam, vel egestas dolor quam sit amet metus. Quisque et elit eget metus fermentum eleifend. In faucibus gravida urna. Quisque aliquam eleifend fringilla. Suspendisse potenti. Donec sed enim ultrices, dapibus orci quis, rhoncus magna.\n' +
      '\n' +
      'Aenean in pretium orci. Ut tincidunt lectus ac ante finibus dignissim. Proin facilisis orci mi, at tincidunt elit luctus non. Curabitur et odio in eros blandit hendrerit. Vestibulum consequat eros sed semper fermentum. Sed consequat dui libero, eu blandit risus molestie ut. Sed dolor nisi, dictum in tellus ut, imperdiet ultricies sem. Nunc vel lacus a elit aliquet semper. Sed elementum elit quis aliquet feugiat. Morbi mattis nisl quis augue mollis pharetra sed vel mi. Pellentesque at tempus tortor. Cras ut lacus condimentum, varius ligula vitae, pharetra elit. Cras condimentum rhoncus velit, sit amet interdum quam mollis vel.\n' +
      '\n' +
      'Fusce in tempus ante, id euismod nulla. Morbi a purus eu nisi luctus commodo vel at nulla. Nulla tortor dui, tempus non fermentum eget, fringilla vitae augue. Duis blandit tincidunt tincidunt. Integer urna diam, dapibus id massa ultricies, imperdiet maximus sem. Quisque ultricies mattis felis, sit amet finibus dolor placerat at. Nunc odio tellus, convallis vitae viverra in, sagittis in odio. Nullam eu tortor eget ligula pharetra lobortis.\n' +
      '\n' +
      'Nam luctus ante quis enim posuere, id hendrerit leo lobortis. Aenean elementum a arcu vitae gravida. Maecenas dapibus accumsan dignissim. Mauris non dapibus ipsum. Morbi euismod semper urna accumsan finibus. Nullam eu augue suscipit, dignissim risus accumsan, volutpat est. Nullam fermentum vel ante a ornare. Ut ornare orci ut sodales rutrum. Donec faucibus lacus id nisi accumsan interdum. Morbi consequat mi justo, quis condimentum nulla scelerisque quis. Vivamus dictum nec lacus quis laoreet. In pulvinar dui libero, ut tempus nisl sodales sagittis. Vestibulum at pulvinar velit. Pellentesque sed turpis nulla. Pellentesque tristique, risus in elementum feugiat, velit sem mollis mi, eu elementum mauris odio a orci. Proin pellentesque euismod nisi ut venenatis.\n' +
      '\n' +
      'Vivamus ut suscipit orci. Cras consequat nisl vitae dui dapibus condimentum ut eu nisl. Ut aliquam dignissim tristique. Donec tristique purus eget odio dapibus viverra. Etiam vulputate pulvinar faucibus. Aliquam vel erat vitae nisi luctus rutrum. Integer rhoncus massa vitae lorem vestibulum, eget feugiat dui tristique. Nullam commodo quis nunc quis vehicula. Etiam mollis risus nulla, eu eleifend dui efficitur vestibulum. Maecenas quis leo dapibus sapien tincidunt interdum. Integer cursus sapien sit amet nisl mollis pretium. Sed id scelerisque nibh. Curabitur interdum vulputate posuere. Nam sed finibus augue.\n' +
      '\n' +
      'In consectetur a arcu vel tincidunt. Proin tincidunt lectus ut luctus aliquam. Nunc consectetur, arcu ac lobortis mollis, risus arcu condimentum magna, laoreet ultricies enim augue id mauris. Integer sed augue dapibus turpis vestibulum scelerisque in sit amet sem. In justo sem, aliquet et suscipit et, euismod eu odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis nisl fermentum, tempor velit id, aliquet lacus. In et velit vel sem lobortis vulputate at ac purus. Ut ornare hendrerit pellentesque. Donec vitae cursus mi. Nullam in enim vitae mauris pharetra faucibus. Duis vulputate sem non purus pretium consectetur. Morbi ac sollicitudin augue, varius pellentesque risus. Quisque ultrices, nisi non volutpat commodo, elit urna ullamcorper arcu, at fringilla odio arcu non magna. Aliquam eget odio egestas, ultricies nibh vitae, aliquet ligula.\n' +
      '\n' +
      'Morbi placerat odio in sapien semper, non cursus diam cursus. Donec euismod et erat eget vehicula. Vivamus porta neque justo. Etiam eget hendrerit ex. Proin fermentum commodo tellus ac efficitur. Praesent molestie augue felis, at maximus felis tempus eu. Nullam nec semper ante. Duis sagittis mauris eu tincidunt vehicula. Nunc sed quam eget leo dapibus dapibus sed id elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi vel vulputate nisl, id semper tortor. Sed fringilla ultricies velit sed placerat. Vestibulum id placerat est. Suspendisse in turpis id purus viverra ultrices. Etiam vitae libero ut tellus molestie hendrerit dictum id libero. Nullam eget mauris quis odio lobortis pretium sed eu sem.\n' +
      '\n' +
      'Morbi hendrerit eget sapien et sodales. Morbi sed ipsum eu lacus egestas gravida a semper arcu. Phasellus iaculis, neque non faucibus mattis, nisi magna dictum urna, nec feugiat metus diam at nisi. Donec eget metus dictum, ultrices neque sit amet, rutrum erat. Sed augue ante, rutrum a fringilla sit amet, venenatis id augue. Vivamus id fermentum sem, a lobortis arcu. Nullam sit amet venenatis odio. Suspendisse rutrum nulla in feugiat pellentesque. Nullam semper placerat scelerisque. Aenean quis turpis bibendum, accumsan nunc at, bibendum orci. Suspendisse vehicula sem non risus sodales vestibulum. Proin sit amet odio ornare, tincidunt lacus efficitur, fermentum lacus. Quisque eget blandit turpis, vitae posuere nulla.\n' +
      '\n' +
      'Duis hendrerit sollicitudin enim eu ornare. Fusce lacus erat, aliquam non eros vel, ultricies bibendum libero. Quisque commodo commodo libero, id sollicitudin lacus posuere et. Duis ut feugiat nulla, at faucibus purus. Cras eu eros felis. Phasellus quis augue urna. Nunc elementum lorem neque, eget scelerisque augue dictum vel. Quisque nec rhoncus nisi. Cras accumsan eleifend imperdiet. Nulla auctor cursus ante, non elementum ligula dignissim nec. Proin sed placerat sem. Maecenas dignissim purus id justo sollicitudin, eu mollis justo consectetur. Duis ultricies magna nibh, at placerat leo finibus ac. Proin lobortis nec dui id ultricies. Curabitur quis consequat nibh.\n' +
      '\n' +
      'Etiam in enim sit amet ligula aliquet cursus. Nullam tempus neque non tortor varius scelerisque. Quisque ac molestie diam. Integer quis justo sit amet eros imperdiet egestas. Suspendisse nulla nibh, blandit sit amet enim eget, iaculis volutpat velit. Pellentesque venenatis lorem sed eleifend convallis. Cras feugiat libero a magna fermentum bibendum.\n' +
      '\n' +
      'Curabitur euismod et neque ac congue. Mauris vulputate libero in venenatis ultricies. Vivamus et orci nisi. Nam at placerat quam. Suspendisse potenti. Sed quis auctor quam. Vestibulum euismod rhoncus ex at commodo. Vestibulum at turpis nisl. Integer volutpat, tortor ac condimentum dapibus, leo eros dignissim sapien, ac malesuada turpis magna id risus. Sed lectus mauris, ultrices eu dapibus a, congue at nibh. Maecenas vel sem non dui sollicitudin rhoncus.\n' +
      '\n' +
      'Suspendisse nunc lorem, sagittis at leo sit amet, ultrices fringilla purus. Fusce neque ligula, tempus quis lorem vitae, tincidunt tempus augue. Vivamus eget nunc eget magna faucibus iaculis. Maecenas sit amet porttitor neque, vel accumsan risus. Ut molestie nisi quis est dictum aliquet. Ut lectus velit, fermentum eu ante eget, vulputate luctus magna. Donec consectetur iaculis lobortis. Fusce ultricies nisi elit, at tincidunt ante viverra posuere. Quisque neque magna, gravida et tincidunt non, tempus blandit tortor.\n' +
      '\n' +
      'Sed at luctus justo. Maecenas vel sem orci. Maecenas porttitor viverra libero, vel rhoncus turpis finibus et. Ut efficitur tortor nec congue volutpat. Vivamus vitae sem ipsum. In enim augue, ultrices at fringilla vulputate, porta nec diam. Mauris eget erat sit amet nisl efficitur tristique ut eget tellus. Pellentesque at elementum metus. Fusce et nisi bibendum, imperdiet nisi eget, venenatis massa. Nam quis est eu neque feugiat sollicitudin ac ut est. Phasellus placerat nibh non congue pharetra.\n' +
      '\n' +
      'Ut in luctus lectus. Nullam at nisi vel arcu consequat faucibus. Etiam eget magna ex. Morbi sit amet aliquam velit. Nam odio mi, viverra interdum sagittis ac, luctus nec purus. Donec sagittis sagittis quam vitae sodales. Ut ac orci consectetur, imperdiet purus in, consectetur tortor. Proin sit amet vehicula eros. Mauris pellentesque sapien porttitor, placerat sapien at, ullamcorper arcu. Duis sollicitudin eleifend neque, et egestas augue dapibus et.\n' +
      '\n' +
      'Sed tellus nunc, scelerisque ut odio nec, congue dapibus risus. Pellentesque dictum lacus malesuada neque congue iaculis. Curabitur blandit rutrum sapien, eget facilisis sem auctor eget. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer lectus massa, aliquam et mauris vitae, consequat dignissim sem. Morbi rhoncus justo nec metus blandit porta. Nullam sed tincidunt quam. Morbi et sollicitudin enim.\n' +
      '\n' +
      'Cras orci leo, consequat vitae nulla sit amet, elementum rutrum felis. Nam luctus rutrum mi in condimentum. Phasellus elit sem, volutpat vehicula ante vel, aliquam sagittis urna. Phasellus pretium nisl non lorem sagittis, id ullamcorper purus feugiat. Nullam neque arcu, lacinia vitae est pharetra, aliquam suscipit lectus. Proin sem lorem, efficitur ut hendrerit at, tincidunt eget orci. Sed ullamcorper magna ut vehicula pretium. Donec eu sapien id nisi dapibus tincidunt. Praesent cursus et lacus vel efficitur. Donec finibus odio est, sit amet lobortis mauris pellentesque sit amet. Mauris vitae sem imperdiet, mattis urna ac, maximus arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam elit dolor, commodo eget egestas imperdiet, ultricies nec quam. Proin lorem elit, consectetur sed molestie a, tempor vitae erat.\n' +
      '\n' +
      'Cras cursus ac quam sit amet ullamcorper. Nam vestibulum enim eget mi sollicitudin gravida. Praesent diam lorem, ornare ut mattis sit amet, gravida eu lorem. Maecenas tempor ut massa et luctus. Curabitur sit amet est lorem. Suspendisse cursus lacinia ornare. Cras non imperdiet urna, at aliquam lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis commodo nisl quis diam molestie elementum. Proin id nibh magna. Curabitur mollis velit a fringilla lacinia. Donec maximus massa vitae magna sollicitudin varius. Duis elementum eleifend mi eu fringilla. Quisque eget consectetur ipsum. Quisque mattis libero in mi pulvinar, sed hendrerit tortor condimentum. Maecenas lacinia luctus lacus, vitae lobortis quam facilisis consectetur.\n' +
      '\n' +
      'Sed eget pellentesque lacus, id iaculis diam. Ut porta sagittis mi. Maecenas blandit dolor in aliquam tempus. Fusce eu tortor quis sem vestibulum fermentum eu lacinia turpis. Donec vel tincidunt metus. Phasellus mauris turpis, ullamcorper vel ornare non, sodales consectetur augue. Aenean sollicitudin velit libero. Ut nec molestie eros. Ut laoreet semper scelerisque.\n' +
      '\n' +
      'Vestibulum commodo lacus vitae libero hendrerit, ac venenatis ex vestibulum. Fusce venenatis faucibus ipsum, suscipit semper tortor pharetra eu. Etiam egestas libero mauris, ac fringilla urna feugiat non. Praesent lobortis libero et lectus sagittis, sit amet bibendum lorem hendrerit. Aliquam feugiat placerat nibh quis viverra. Suspendisse non lacus volutpat, egestas ante quis, bibendum ligula. Maecenas viverra efficitur viverra. Sed in hendrerit dui. Mauris bibendum metus a porttitor pharetra. Ut porttitor metus a dui fermentum tincidunt. Nunc a dignissim est. Nullam vel sodales felis. Etiam rutrum pulvinar viverra. Aenean et nisi condimentum, rhoncus mauris ac, pharetra quam.\n' +
      '\n' +
      'Nunc a fermentum leo, porttitor efficitur dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam sit amet mi ac erat venenatis volutpat nec non leo. Fusce eleifend, tellus sit amet fringilla efficitur, tortor elit cursus magna, sit amet malesuada magna nibh vel sem. Nam sagittis magna ante, non ultricies eros ornare vitae. Vestibulum elementum tincidunt lectus vel rutrum. Vestibulum lobortis massa dolor. Maecenas et nunc at neque finibus efficitur sit amet pharetra felis. Nunc a arcu a nisl sollicitudin dignissim at vitae mi. Aliquam lobortis vehicula urna eu tincidunt. Sed consectetur tellus sit amet luctus viverra.\n' +
      '\n' +
      'In consequat elit at odio tristique, id convallis sapien finibus. Sed pretium magna eu libero auctor mattis. Curabitur nec interdum mauris. Nulla id diam dignissim, auctor orci non, ultrices enim. Nulla dolor ante, hendrerit in mollis at, hendrerit eget erat. Sed elementum mollis vestibulum. Praesent nec fringilla mi. Nulla lacus metus, egestas at egestas vitae, vestibulum vel est. Donec rutrum eleifend libero sit amet tempor. Praesent malesuada ex in elit feugiat vulputate. Etiam augue libero, dignissim vitae volutpat a, ultricies eget tortor. Nam semper est fringilla aliquet maximus. Donec consectetur a libero vitae euismod. Mauris tristique, nibh in facilisis tempus, arcu nisi efficitur neque, ac consequat felis urna eget risus. Vestibulum quis rhoncus sem.\n' +
      '\n' +
      'Curabitur non metus et nulla imperdiet pellentesque. Sed vehicula, mi non porttitor mollis, felis dui porttitor orci, eu imperdiet turpis purus eget enim. Proin est velit, blandit nec volutpat et, euismod eu elit. In sapien leo, scelerisque bibendum justo at, consequat imperdiet libero. Nulla laoreet placerat leo eget sollicitudin. Mauris at ante ut augue eleifend egestas. Fusce ut imperdiet erat. Curabitur maximus, est dapibus euismod tristique, magna sem sollicitudin sem, a pulvinar lorem tortor et dolor. Mauris congue leo convallis ipsum dictum, quis euismod eros sodales. Sed rhoncus elementum mollis. Nulla eu dictum arcu. Morbi mollis, arcu non porta posuere, erat dolor pharetra quam, sit amet maximus mauris ligula vitae magna. Donec sodales dapibus lacus, sed varius magna molestie in. Aliquam a ipsum dapibus, condimentum quam a, fringilla felis.\n' +
      '\n' +
      'In vitae magna vulputate, consequat lectus et, hendrerit nisl. Proin rutrum augue ac tincidunt lacinia. Donec eget nulla eu sapien sodales pellentesque. Aliquam suscipit, nisi vel ultrices vulputate, quam sem pellentesque enim, in viverra massa elit consequat arcu. Quisque dignissim pulvinar elementum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sit amet nisl eleifend, gravida odio pretium, euismod ex. Cras ultrices quam eget est elementum bibendum. Nulla ultricies nulla ex, non interdum leo rhoncus a.\n' +
      '\n' +
      'Phasellus justo est, luctus vel placerat sed, euismod a felis. Pellentesque sit amet cursus neque. Donec dignissim enim lacus, at congue elit consequat vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ut tortor non lorem lacinia aliquam non quis augue. Donec ullamcorper placerat dui et vehicula. Ut congue, dui at porttitor rutrum, nibh velit sollicitudin orci, sed scelerisque enim enim id nisl. Donec metus ante, aliquet eu accumsan a, fringilla sed ipsum.\n' +
      '\n' +
      'Morbi in velit at mi viverra posuere quis quis quam. Nullam aliquet porttitor fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas sollicitudin quis velit ut bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec porttitor vitae tellus ut varius. Ut hendrerit ultricies magna, vitae bibendum ex mattis ac. Pellentesque mattis ipsum eu turpis ultrices interdum. Ut ornare sapien sed dui finibus, vel blandit ipsum sagittis. Sed finibus mauris non urna pellentesque, ut tempus dolor facilisis. Integer lacus libero, congue in libero at, elementum varius tortor.\n' +
      '\n' +
      'Suspendisse a massa id lectus eleifend faucibus eu ac nisl. Nam finibus leo sed posuere volutpat. Sed at orci eget risus porttitor dictum at sed quam. Nunc urna sem, finibus fermentum rutrum nec, scelerisque sed dui. Nunc pulvinar purus egestas, semper est at, auctor augue. Phasellus ut ex eget nisi accumsan ultrices at id magna. In hac habitasse platea dictumst. Vivamus blandit interdum pellentesque.\n' +
      '\n' +
      'Ut lacus massa, suscipit id consectetur non, pellentesque vitae massa. Nullam mattis lorem arcu, ac scelerisque ante congue id. Ut volutpat at ligula a efficitur. Donec ac ante felis. Quisque facilisis lorem vitae libero dignissim, eu ultrices nibh feugiat. Nunc sit amet massa eu quam interdum vulputate. Duis suscipit magna massa, id euismod neque vehicula convallis. Duis malesuada, ipsum sed bibendum elementum, lorem dolor consectetur leo, id eleifend risus dui quis lacus. Vestibulum nibh dolor, dictum id arcu consectetur, imperdiet varius neque.\n' +
      '\n' +
      'Integer hendrerit neque enim, sodales faucibus diam congue sed. Nulla facilisi. Nunc interdum metus in dolor imperdiet maximus. Ut in luctus enim, tincidunt commodo eros. Praesent suscipit eros finibus commodo pretium. Morbi condimentum placerat magna, quis ullamcorper ligula tincidunt in. Donec faucibus dui lacinia dolor sollicitudin, tempus fermentum odio porttitor. Suspendisse ac dui nunc. Donec nec arcu ac metus consectetur fringilla. Vivamus faucibus, neque eget tincidunt accumsan, lorem erat varius neque, et blandit nisi lectus id justo.\n' +
      '\n' +
      'Praesent eget mauris justo. Donec fringilla eu augue a tincidunt. Nulla rhoncus est quis ante egestas pellentesque. Morbi ornare eros non purus mollis, eu volutpat elit ultrices. Curabitur egestas libero sed libero luctus, at feugiat turpis vulputate. Suspendisse tincidunt cursus congue. Vivamus sodales tincidunt sapien, eu vehicula tortor fermentum et. Vivamus tempus a est et condimentum. Maecenas non neque vitae velit euismod finibus. Cras ut vehicula velit.\n' +
      '\n' +
      'Etiam efficitur urna ut semper sodales. Suspendisse tincidunt nisi vel tincidunt scelerisque. Fusce eget odio iaculis neque sodales malesuada. Cras mattis fermentum semper. Nulla pretium risus turpis, sit amet ultrices sapien faucibus nec. Nulla eu ultrices leo. Quisque et nisi nulla. Nam consectetur aliquet massa, nec laoreet lorem consequat sed. Fusce non semper dui. Fusce ornare vel dolor eu consequat. Aliquam cursus a dui vel mattis.\n' +
      '\n' +
      'Etiam sit amet sem et ligula fringilla ornare. In sollicitudin nunc mauris. Cras in ligula in nisi rutrum pellentesque. Vivamus porttitor lacus ex, sit amet consequat mi pretium vitae. Curabitur pellentesque enim lacus, sit amet condimentum ante egestas eu. Donec laoreet, orci non finibus dictum, metus leo facilisis enim, quis lobortis nisl nibh id magna. Sed arcu dolor, maximus at tellus ac, consequat ullamcorper odio. Nullam scelerisque, massa vel feugiat accumsan, magna enim elementum dui, ac consectetur nulla lectus ac sem. Aenean venenatis laoreet egestas. Aliquam in tortor lacus. Aenean commodo iaculis justo, quis aliquam libero fringilla eget. Nunc nec purus sapien. In hac habitasse platea dictumst. Vivamus faucibus varius laoreet.\n' +
      '\n' +
      'In imperdiet finibus quam vel tempor. Nunc ut odio vitae lorem mollis lobortis eu vitae sem. Pellentesque tempus lorem non dui imperdiet, at congue ex tempus. Morbi et leo in urna accumsan efficitur. Vestibulum dapibus at urna efficitur sollicitudin. Ut vitae tincidunt sapien. Nunc consectetur aliquet libero non consectetur. Nunc in rutrum ante. Donec nibh orci, lacinia in euismod eu, viverra ac magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut urna libero, aliquam id ultrices a, rhoncus quis quam.\n' +
      '\n' +
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean iaculis eu felis at euismod. Vestibulum id nibh turpis. Nam semper libero et neque suscipit feugiat. Sed sagittis justo vel erat suscipit, ut facilisis elit mattis. Donec egestas purus eget lobortis dignissim. Nullam tincidunt diam posuere lectus ornare, sit amet interdum nisl facilisis.\n' +
      '\n' +
      'Mauris laoreet diam hendrerit turpis rhoncus, nec aliquet arcu gravida. Integer at tellus ut magna commodo sollicitudin. Vestibulum venenatis arcu quis tempor fermentum. Sed vitae tempus nisl, id feugiat ex. In sodales varius erat, sit amet consectetur est tempus a. Donec in ligula nec mauris lacinia fringilla. Maecenas ut dictum est. Mauris tincidunt commodo nulla, cursus elementum mauris.\n' +
      '\n' +
      'Suspendisse velit justo, sodales vitae dolor at, imperdiet mollis risus. Mauris aliquet luctus mollis. Vestibulum at enim tempor, suscipit massa et, finibus ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas sed porta tortor. Proin ornare, sapien id tempus gravida, lorem nibh gravida erat, ut rhoncus sem mi at augue. Aliquam euismod commodo finibus. Curabitur ipsum ipsum, ornare eget vehicula sit amet, tincidunt nec mauris. Morbi congue lorem at vehicula lacinia. Maecenas libero libero, cursus vel volutpat et, tempus at nunc. Curabitur tempor quis felis ac dapibus.\n' +
      '\n' +
      'Aenean gravida tellus purus, id feugiat odio lacinia eu. Suspendisse potenti. Donec ornare nunc libero, quis luctus nisi dignissim non. Donec commodo ac leo sit amet feugiat. Sed sit amet auctor neque, blandit porttitor felis. Pellentesque at neque eu est auctor mollis nec vitae ante. Nullam ullamcorper nulla nunc, vitae volutpat enim dapibus non. Nulla aliquam eget augue quis aliquam.\n' +
      '\n' +
      'Donec vitae justo imperdiet, aliquet ex non, viverra mi. Nulla et scelerisque mi, ac molestie felis. Pellentesque quis lectus a mi hendrerit vestibulum lobortis congue dui. Phasellus dictum ultrices arcu sed faucibus. Nulla odio lectus, imperdiet in turpis sit amet, facilisis vehicula tortor. Vivamus ut magna est. Duis at tortor id neque ultrices fermentum maximus nec tortor. Morbi pellentesque tellus nec sem vulputate ullamcorper. Cras semper consequat libero in condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque auctor, sapien vel pulvinar pellentesque, mauris risus elementum magna, sit amet lacinia justo lectus non massa.\n' +
      '\n' +
      'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent cursus tempus odio, eget eleifend felis vulputate vitae. Nullam rhoncus bibendum lacus sed feugiat. In quis felis sed ante sodales fermentum sed vel sapien. Duis gravida in mi a hendrerit. Etiam ut massa hendrerit, rhoncus diam nec, dictum libero. Pellentesque id placerat sem.\n' +
      '\n' +
      'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla in commodo urna. Phasellus quam lorem, scelerisque vitae eleifend eget, tristique ac orci. Quisque placerat sit amet odio vitae vehicula. Aenean aliquam nulla vitae odio vehicula tempus. Nulla hendrerit a mauris nec eleifend. Donec fringilla elit non commodo lacinia. Nullam bibendum, risus non efficitur aliquam, erat orci sollicitudin tortor, quis ultrices risus leo a elit.\n' +
      '\n' +
      'instagram.com/?querystring',
  );
} else {
  ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    document.getElementById('root'),
  );
}

const appHeight = () => {
  const doc = document.documentElement;
  doc.style.setProperty('--app-height', `${window.innerHeight}px`);
};

appHeight();
window.addEventListener('resize', appHeight);

serviceWorker.unregister();
